# Import templates
include:
  project: internal/ci-templates
  file:
    - /templates/.gitlab-ci-build.yml
    - /templates/.gitlab-ci-deploy.yml

stages:
  - build
  - deploy

deployment:
  only:
    - master
  stage: deploy
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  when: on_success
  script:
    - ansible-playbook -i static_inventory/hetzner tom.yml -e root_domain=tom.infrapu.sh -e tag=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID -t docker-app -e 'target_app=tom'
