version: "3.9"

services:
  live-reload:
    image: apogiatzis/livereloading
    container_name: live-reload
    privileged: true
    environment:
      - RELOAD_DELAY=1
      - RELOAD_CONTAINER=api_dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /api/src:/usr/app/src
